name: Cache File Example

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print "steps.adam.outputs.cache-hit != 'true'"
        run: |
          echo "Cache Hit Value:"  ${{ steps.adam.outputs.cache-hit }}

      - name: Run your build step
        run: |
          mv hello_world.py ./data/
          ls
          python ./data/hello_world.py

      - name: Cache Dataset
        uses: actions/cache@v3
        id: adam
        with:
          path: ./data/hello_world.py  # Specify the path to the file you want to cache
          key: ${{ runner.os }}-${{ hashFiles('./hello_world.py') }}  # Cache key based on the operating system